import type { WizardConfig } from '../types/wizard';

export function generateGitHubWorkflow(cfg: WizardConfig): string {
  const clusterName = cfg.clusterName || 'my-aks-cluster';
  const resourceGroup = cfg.resourceGroupName || 'my-aks-rg';
  const registry = cfg.containerRegistryName || 'myregistry';
  const hasAcr = cfg.enableAcrIntegration && cfg.containerRegistryName;

  const acrLoginStep = hasAcr
    ? `
      - name: Log in to Azure Container Registry
        run: az acr login --name ${registry}`
    : '';

  const k8sBakeStep = `
      - name: Bake Kubernetes manifests
        uses: azure/k8s-bake@v3
        id: bake
        with:
          renderType: helm
          helmChart: ./charts/app
          overrideFiles: ./charts/app/values-\${{ github.ref_name }}.yaml
          helm-version: latest`;

  const imagePullSecretStep = hasAcr
    ? `
      - name: Create image pull secret for ACR
        uses: azure/k8s-create-secret@v5
        with:
          namespace: default
          secret-type: docker-registry
          secret-name: acr-pull-secret
          container-registry-url: ${registry}.azurecr.io
          container-registry-username: \${{ secrets.ACR_USERNAME }}
          container-registry-password: \${{ secrets.ACR_PASSWORD }}`
    : '';

  return `# GitHub Actions CI/CD Pipeline — generated by AKS Wizard
# Deploys to AKS cluster: ${clusterName} in resource group: ${resourceGroup}
#
# Required repository secrets:
#   AZURE_CREDENTIALS   – Service principal JSON from: az ad sp create-for-rbac --sdk-auth
#   KUBE_CONFIG         – Base64-encoded kubeconfig (or use azure/aks-set-context)
${hasAcr ? '#   ACR_USERNAME        – ACR admin username (or use managed identity)\n#   ACR_PASSWORD        – ACR admin password' : ''}

name: Deploy to AKS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CLUSTER_NAME: ${clusterName}
  RESOURCE_GROUP: ${resourceGroup}
  NAMESPACE: default
${hasAcr ? `  REGISTRY: ${registry}.azurecr.io` : ''}

jobs:
  # ─── Validate manifests on every PR ─────────────────────────────────────────
  validate:
    name: Validate Kubernetes Manifests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Lint Helm chart
        run: helm lint ./charts/app

      - name: Dry-run Kubernetes manifest bake
        uses: azure/k8s-bake@v3
        with:
          renderType: helm
          helmChart: ./charts/app
          helm-version: latest

  # ─── Build and push container image ─────────────────────────────────────────
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/main'
    outputs:
      image-tag: \${{ steps.meta.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: \${{ secrets.AZURE_CREDENTIALS }}
${acrLoginStep}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${hasAcr ? `${registry}.azurecr.io/app` : 'ghcr.io/${{ github.repository }}'}
          tags: |
            type=sha,prefix=,suffix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: \${{ steps.meta.outputs.tags }}

  # ─── Deploy to AKS ───────────────────────────────────────────────────────────
  deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: https://\${{ env.CLUSTER_NAME }}.azurefd.net
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: \${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: \${{ env.RESOURCE_GROUP }}
          cluster-name: \${{ env.CLUSTER_NAME }}
${imagePullSecretStep}
${k8sBakeStep}

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v5
        with:
          namespace: \${{ env.NAMESPACE }}
          manifests: \${{ steps.bake.outputs.manifestsBundle }}
          images: |
            ${hasAcr ? `${registry}.azurecr.io/app` : 'ghcr.io/${{ github.repository }}'}: \${{ needs.build.outputs.image-tag }}
${hasAcr ? `          imagepullsecrets: |
            acr-pull-secret` : ''}

  # ─── AKS Upgrade notification ────────────────────────────────────────────────
  check-aks-upgrades:
    name: Check AKS Available Upgrades
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: \${{ secrets.AZURE_CREDENTIALS }}

      - name: List available AKS upgrades
        run: |
          echo "### Available AKS upgrades for ${clusterName} ###"
          az aks get-upgrades \\
            --resource-group ${resourceGroup} \\
            --name ${clusterName} \\
            --output table || echo "Could not retrieve upgrade info (cluster may not exist yet)"
`;
}
