import type { WizardConfig } from '../types/wizard';

export function generatePowerShell(cfg: WizardConfig): string {
  const clusterName = cfg.clusterName || 'my-aks-cluster';
  const rg = cfg.resourceGroupName || 'my-resource-group';
  const region = cfg.region || 'eastus';
  const dnsPrefix = cfg.dnsPrefix || clusterName;
  const k8sVersion = cfg.kubernetesVersion || '1.29.x';

  const autoScaleArgs = cfg.systemNodePool.enableAutoScaling
    ? `\`
    --enable-cluster-autoscaler \`
    --min-count ${cfg.systemNodePool.minNodes} \`
    --max-count ${cfg.systemNodePool.maxNodes}`
    : `\`
    --node-count ${cfg.systemNodePool.nodeCount}`;

  const networkPolicyArg =
    cfg.networkPolicy !== 'None' ? `\`\n    --network-policy ${cfg.networkPolicy}` : '';

  const aadArgs = cfg.enableAzureAd && cfg.azureAdTenantId
    ? `\`\n    --enable-aad \`\n    --aad-tenant-id '${cfg.azureAdTenantId}'`
    : '';

  const rbacArg = cfg.enableRbac ? ' `\n    --enable-rbac' : '';

  const monitoringArg = cfg.enableContainerInsights
    ? `\`\n    --enable-addons monitoring${cfg.logAnalyticsWorkspaceId ? ` \`\n    --workspace-resource-id '${cfg.logAnalyticsWorkspaceId}'` : ''}`
    : '';

  const addonsArg = [
    cfg.enableHttpApplicationRouting ? '`\n    --enable-addons http_application_routing' : '',
    cfg.enableAzurePolicy ? '`\n    --enable-addons azure-policy' : '',
  ].filter(Boolean).join(' ');

  const optionalArgs = [rbacArg, aadArgs, networkPolicyArg, monitoringArg, addonsArg]
    .filter(Boolean)
    .join('');

  const userNodePoolSection = cfg.userNodePools.length > 0
    ? cfg.userNodePools
        .map((pool) => {
          const poolAutoScale = pool.enableAutoScaling
            ? `--enable-cluster-autoscaler --min-count ${pool.minNodes} --max-count ${pool.maxNodes}`
            : `--node-count ${pool.nodeCount}`;
          return `
# Add user node pool: ${pool.name}
az aks nodepool add \`
    --resource-group $ResourceGroup \`
    --cluster-name $ClusterName \`
    --name '${pool.name}' \`
    --node-vm-size '${pool.vmSize}' \`
    ${poolAutoScale} \`
    --mode User`;
        })
        .join('\n')
    : '';

  return `<#
.SYNOPSIS
    Deploys an Azure Kubernetes Service (AKS) cluster using the configuration
    generated by AKS-Wizard.

.DESCRIPTION
    This script creates the resource group (if it does not exist) and provisions
    an AKS cluster with the settings configured in the AKS-Wizard.

    Prerequisites:
      - Azure CLI (az) installed and available on PATH
      - PowerShell 7+ (or Windows PowerShell 5.1)
      - Sufficient Azure subscription permissions (Contributor or Owner)

    Usage:
      .\\deploy-aks.ps1
      .\\deploy-aks.ps1 -SubscriptionId '<your-subscription-id>'

.NOTES
    ⚠️  Educational Disclaimer: This script is provided for educational and
    learning purposes only. Validate and tailor it for your own production
    environment before use.
#>

[CmdletBinding()]
param (
    [string]$SubscriptionId = '${cfg.subscriptionId || '<YOUR-SUBSCRIPTION-ID>'}',
    [string]$ResourceGroup  = '${rg}',
    [string]$ClusterName    = '${clusterName}',
    [string]$Region         = '${region}'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── 1. Login & set subscription ───────────────────────────────────────────────
Write-Host "🔐 Logging in to Azure..." -ForegroundColor Cyan
az login --output none

Write-Host "📌 Setting subscription to $SubscriptionId" -ForegroundColor Cyan
az account set --subscription $SubscriptionId

# ── 2. Create Resource Group ──────────────────────────────────────────────────
Write-Host "📦 Creating resource group '$ResourceGroup' in '$Region'..." -ForegroundColor Cyan
az group create \`
    --name $ResourceGroup \`
    --location $Region \`
    --output none

# ── 3. (Optional) Create Log Analytics Workspace ──────────────────────────────${cfg.enableContainerInsights && !cfg.logAnalyticsWorkspaceId ? `
$WorkspaceName = "$ClusterName-law"
Write-Host "📊 Creating Log Analytics Workspace '$WorkspaceName'..." -ForegroundColor Cyan
$WorkspaceId = $(az monitor log-analytics workspace create \`
    --resource-group $ResourceGroup \`
    --workspace-name $WorkspaceName \`
    --location $Region \`
    --query id -o tsv)` : ''}

# ── 4. Create AKS Cluster ─────────────────────────────────────────────────────
Write-Host "🚀 Creating AKS cluster '$ClusterName'..." -ForegroundColor Cyan
az aks create \`
    --resource-group $ResourceGroup \`
    --name $ClusterName \`
    --location $Region \`
    --kubernetes-version ${k8sVersion} \`
    --dns-name-prefix '${dnsPrefix}' \`
    --node-vm-size '${cfg.systemNodePool.vmSize}' ${autoScaleArgs} \`
    --network-plugin '${cfg.networkPlugin}' \`
    --service-cidr '${cfg.serviceCidr}' \`
    --load-balancer-sku '${cfg.loadBalancerSku.toLowerCase()}'${optionalArgs} \`
    --output none

${userNodePoolSection}
# ── 5. Get credentials ────────────────────────────────────────────────────────
Write-Host "🔑 Fetching kubeconfig..." -ForegroundColor Cyan
az aks get-credentials \`
    --resource-group $ResourceGroup \`
    --name $ClusterName \`
    --overwrite-existing

# ── 6. Verify cluster ─────────────────────────────────────────────────────────
Write-Host "✅ Cluster ready! Listing nodes:" -ForegroundColor Green
kubectl get nodes

Write-Host ""
Write-Host "🎉 AKS cluster '$ClusterName' deployed successfully!" -ForegroundColor Green
`;
}
