<#
.SYNOPSIS
    Deploys an Azure Kubernetes Service (AKS) cluster using the Azure CLI.

.DESCRIPTION
    This script creates a resource group (if it does not already exist) and
    provisions an AKS cluster with the parameters you supply. It is designed
    to be generated by the AKS-Wizard web application, but can also be run
    standalone by customising the parameters at the top of the file.

    Prerequisites:
      - Azure CLI (az) v2.40+  https://learn.microsoft.com/cli/azure/install-azure-cli
      - kubectl                 https://kubernetes.io/docs/tasks/tools/
      - PowerShell 7+  OR  Windows PowerShell 5.1

    Quick start:
      1. Open a PowerShell terminal.
      2. Run: az login
      3. Run: .\deploy-aks.ps1 -SubscriptionId '<your-subscription-id>'

.NOTES
    ⚠️  Educational Disclaimer: This script is provided for educational and
    learning purposes only. All content, including examples and documentation,
    should be validated and tailored for your own production environment before use.
#>

[CmdletBinding()]
param (
    # Azure subscription to deploy into
    [Parameter(Mandatory = $true)]
    [string]$SubscriptionId,

    # Name of the resource group (will be created if it does not exist)
    [string]$ResourceGroup = 'my-aks-rg',

    # AKS cluster name
    [string]$ClusterName = 'my-aks-cluster',

    # Azure region
    [string]$Region = 'eastus',

    # Kubernetes version (e.g. 1.29)
    [string]$KubernetesVersion = '1.29',

    # System node pool VM size
    [string]$NodeVmSize = 'Standard_D2s_v3',

    # Initial node count (ignored when autoscaling is enabled)
    [int]$NodeCount = 3,

    # Enable cluster autoscaler
    [switch]$EnableAutoScaling,

    # Minimum node count when autoscaling is enabled
    [int]$MinNodes = 1,

    # Maximum node count when autoscaling is enabled
    [int]$MaxNodes = 5,

    # Container network plugin: 'azure' or 'kubenet'
    [ValidateSet('azure', 'kubenet')]
    [string]$NetworkPlugin = 'azure',

    # Network policy: 'None', 'azure', or 'calico'
    [ValidateSet('None', 'azure', 'calico')]
    [string]$NetworkPolicy = 'None',

    # Enable Container Insights monitoring add-on
    [switch]$EnableMonitoring,

    # Existing Log Analytics Workspace resource ID (optional; a new one is created when omitted)
    [string]$LogAnalyticsWorkspaceId = '',

    # Load balancer SKU: 'Standard' or 'Basic'
    [ValidateSet('Standard', 'Basic')]
    [string]$LoadBalancerSku = 'Standard',

    # Enable Azure AD integration
    [switch]$EnableAzureAD,

    # Azure AD tenant ID (required when EnableAzureAD is set)
    [string]$AadTenantId = ''
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Helpers ───────────────────────────────────────────────────────────────────
function Write-Step([string]$Message) {
    Write-Host "`n⏳  $Message" -ForegroundColor Cyan
}

function Write-Success([string]$Message) {
    Write-Host "✅  $Message" -ForegroundColor Green
}

# ── 1. Set active subscription ────────────────────────────────────────────────
Write-Step "Setting subscription to '$SubscriptionId'..."
az account set --subscription $SubscriptionId
Write-Success "Subscription set."

# ── 2. Create Resource Group ──────────────────────────────────────────────────
Write-Step "Ensuring resource group '$ResourceGroup' exists in '$Region'..."
az group create `
    --name $ResourceGroup `
    --location $Region `
    --output none
Write-Success "Resource group ready."

# ── 3. (Optional) Create Log Analytics Workspace ──────────────────────────────
if ($EnableMonitoring -and [string]::IsNullOrWhiteSpace($LogAnalyticsWorkspaceId)) {
    $WorkspaceName = "$ClusterName-law"
    Write-Step "Creating Log Analytics Workspace '$WorkspaceName'..."
    $LogAnalyticsWorkspaceId = $(az monitor log-analytics workspace create `
        --resource-group $ResourceGroup `
        --workspace-name $WorkspaceName `
        --location $Region `
        --query id -o tsv)
    Write-Success "Workspace created: $LogAnalyticsWorkspaceId"
}

# ── 4. Build az aks create arguments ─────────────────────────────────────────
$aksArgs = @(
    'aks', 'create',
    '--resource-group', $ResourceGroup,
    '--name', $ClusterName,
    '--location', $Region,
    '--kubernetes-version', $KubernetesVersion,
    '--dns-name-prefix', $ClusterName,
    '--node-vm-size', $NodeVmSize,
    '--network-plugin', $NetworkPlugin,
    '--load-balancer-sku', $LoadBalancerSku.ToLower(),
    '--enable-rbac',
    '--output', 'none'
)

if ($EnableAutoScaling) {
    $aksArgs += '--enable-cluster-autoscaler', '--min-count', $MinNodes, '--max-count', $MaxNodes
} else {
    $aksArgs += '--node-count', $NodeCount
}

if ($NetworkPolicy -ne 'None') {
    $aksArgs += '--network-policy', $NetworkPolicy
}

if ($EnableAzureAD) {
    if ([string]::IsNullOrWhiteSpace($AadTenantId)) {
        Write-Error "AadTenantId is required when EnableAzureAD is set."
        exit 1
    }
    $aksArgs += '--enable-aad', '--aad-tenant-id', $AadTenantId
}

if ($EnableMonitoring) {
    $aksArgs += '--enable-addons', 'monitoring'
    if (-not [string]::IsNullOrWhiteSpace($LogAnalyticsWorkspaceId)) {
        $aksArgs += '--workspace-resource-id', $LogAnalyticsWorkspaceId
    }
}

# ── 5. Create AKS Cluster ─────────────────────────────────────────────────────
Write-Step "Creating AKS cluster '$ClusterName' (this may take several minutes)..."
az @aksArgs
Write-Success "AKS cluster '$ClusterName' created."

# ── 6. Retrieve kubeconfig ────────────────────────────────────────────────────
Write-Step "Fetching kubeconfig..."
az aks get-credentials `
    --resource-group $ResourceGroup `
    --name $ClusterName `
    --overwrite-existing
Write-Success "Kubeconfig updated."

# ── 7. Verify cluster ─────────────────────────────────────────────────────────
Write-Host ""
Write-Host "Node status:" -ForegroundColor Yellow
kubectl get nodes

Write-Host ""
Write-Success "AKS cluster '$ClusterName' deployed successfully! 🎉"
